on: push
name: Build
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zhangsq/test:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



      # - name: upload-artifacts
        # uses: actions/upload-artifact@v2
        # with:
          # name: test
          # path: bin/*