on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make build
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: bin/test