name: Create Tag
on:
  workflow_dispatch:
    branches: [ main, dev ]

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: true
